# Generated by Django 5.2.7 on 2025-10-28 22:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength Training'), ('YOGA', 'Yoga'), ('SPORTS', 'Sports'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('SWIMMING', 'Swimming'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('intensity', models.IntegerField(choices=[(1, 'Very Light'), (2, 'Light'), (3, 'Moderate'), (4, 'Hard'), (5, 'Very Hard')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calories_burned', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('workout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-workout_date'],
                'indexes': [models.Index(fields=['user', '-workout_date'], name='fitworkouts_user_id_49e356_idx')],
            },
        ),
    ]
