# Generated by Django 5.2.7 on 2025-10-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittracker', '0002_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('Lose', 'Lose Weight'), ('Gain', 'Gain Weight'), ('Maintain', 'Maintain Fitness')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True),
        ),
    ]
