name: ZAP Security Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Elastic Beanstalk"]
    types:
      - completed

jobs:

  wait-for-eb:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ secrets.APP_URL }}
      EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
      EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Wait for Elastic Beanstalk to be Healthy
        run: |
          EB_APP_NAME="${EB_APP_NAME}"
          EB_ENV_NAME="${EB_ENV_NAME}"

          echo "Checking EB environment health..."

          for i in {1..20}; do
            HEALTH=$(aws elasticbeanstalk describe-environments \
              --environment-names "$EB_ENV_NAME" \
              --query "Environments[0].Health" \
              --output text)

            echo "Current EB Health: $HEALTH"

            if [ "$HEALTH" = "Green" ]; then
              echo "Elastic Beanstalk is Healthy."
              exit 0
            fi

            echo "Waiting for 15 seconds..."
            sleep 15
          done

          echo "ERROR: EB did not reach GREEN health."
          exit 1


  zap-scan:
    runs-on: ubuntu-latest
    needs: wait-for-eb
    env:
      TARGET_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        continue-on-error: true
        with:
          target: ${{ env.TARGET_URL }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false
          allow_issue_writing: false
          cmd_options: "-a"